### ISSUE TITLE
Keyword and feature request

### ISSUE THREAD

**Issue by Vasile-Peste** [pouyakary/nearley-vscode#3]
Hi,
thank you for your work.

1. I would like to let you know that the "import" keyword has been replaced with "include", you should add the highlight also for the "include" keyword.

2. You included the "@preprocessor" directive, when the preprocessor directive is used for TypeScript you should enable syntax highlighting for TypeScript inside the inline JavaScript. Now if I use TypeScript as preprocessor, the inline code is considered plain JavaScript and not TypeScript.

Thank you.

**Comment by pouyakary** [comment]
@Vasile-Peste Thanks a lot for letting me know! I haven't have used Nearley for quite a while now. This actually helped a lot!

**Comment by samestep** [comment]
For the second bullet, I'm a bit confused by the current behavior. Even though nearley-vscode seems to explicitly specify JS rather than TS:

https://github.com/pouyakary/nearley-vscode/blob/25b19bfca69a8bb9afda6a2f2df3df8f279ce1f0/syntaxes/nearley.tmLanguage.json#L76

the actual resulting scopes seem to be TS:

<img width="745" alt="JS" src="https://user-images.githubusercontent.com/8246041/147664460-b2b2b3d4-ae3b-4508-99b8-fbfaf4f39213.png">

And indeed, correct syntax highlighting seems to be given even when I use TS syntax that doesn't exist in JS:

<img width="899" alt="TS" src="https://user-images.githubusercontent.com/8246041/147664810-34057022-5394-4a16-9911-14de60458a00.png">

So it seems like VS Code might already have some magic that makes this a non-issue?

**Comment by samestep** [comment]
Oh, I think now I understand:

https://github.com/pouyakary/nearley-vscode/blob/25b19bfca69a8bb9afda6a2f2df3df8f279ce1f0/syntaxes/nearley.tmLanguage.json#L76-L81

https://github.com/pouyakary/nearley-vscode/blob/25b19bfca69a8bb9afda6a2f2df3df8f279ce1f0/package.json#L33-L36

So it looks like currently these `inlinejs` blocks are always interpreted as TypeScript rather than JavaScript? This seems like it should work fine since generally TypeScript is considered a "superset" of JavaScript. I'm guessing it'd work less well for `@preprocessor coffee`, but I'm guessing not many people are using CoffeeScript with nearley in VS Code anyway.

**Comment by pouyakary** [comment]
@samestep hello Sam, I've been looking at your PRs for the past few days. And thanks a lot for them. I used TypeScript since yeah I though if I use that, it will cover both TypeScript and JavaScript. But for cases of using Coffee.... I have no idea. I guess we could ship other grammars and define languages like: "Nearley - CoffeeScript" ?

**Comment by samestep** [comment]
Yep, makes sense! I suppose you could ship a "Nearley - CoffeeScript" language if there's demand for it (I don't need it, personally), but in that case I guess you'd need a way to automatically choose which one to use by looking for a `@preprocessor coffee` directive? I don't know enough about VS Code language extensions to know how to do that off the top of my head, though.
