### ISSUE TITLE
Typing % inserts %%

### ISSUE THREAD

**Issue by mspoulsen** [pouyakary/nearley-vscode#5]
When I type % then %% is inserted.

Thanks!

**Comment by hildjj** [comment]
That looks intentional, from https://github.com/pouyakary/nearley-vscode/blob/25b19bfca69a8bb9afda6a2f2df3df8f279ce1f0/language-configuration.json#L6

But as soon as I switched to using a moo lexer, as shown in the [docs](https://nearley.js.org/docs/tokenizers#lexing-with-moo), it became clear that the current behavior doesn't match my workflow.

**Comment by pouyakary** [comment]
Ah I see. I will remove this.
